version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: expuser
      POSTGRES_PASSWORD: exppass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expensetracker
      SPRING_DATASOURCE_USERNAME: expuser
      SPRING_DATASOURCE_PASSWORD: exppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
